remote_theme: pmarsceill/just-the-docs

title: Anglo-Catholic Resources
description: A repository of everything related to the Anglo-Catholic tradition

plugins:
  - jekyll-seo-tag
twitter:
  username: dylancdoherty
